### PR TITLE
:b:ull re:b:uest #8 lol

### PR DESCRIPTION
**Pull request by apap04**
- [x] Make the login thing partially work.
- [x] Make a custom title bar. Cuz ya know, or you don't
- [x] Fix toolbar buttons.

### CODE REVIEW

**Comment by binsenpai** [comment]
wait should i be merging this?

**Comment by apap04** [comment]
nop

**Comment by apap04** [comment]
:feelsgood:

**Comment by apap04** [comment]
@Reaxt00 nothing :feelsgood:

**Comment by apap04** [comment]
im just using :b:ypescript anyway

**Comment by apap04** [comment]
<@323759787588190222> merge

**Comment by binsenpai** [comment]
fuck this shit

**Comment by apap04** [comment]
fuck this shit too

**Pull request merged**
