### PR TITLE
Starter files for otakoclient.

### PR DESCRIPTION
**Pull request by apap04**
I know we're not working on it yet. I'm just getting starter files up so we're ahead.

### CODE REVIEW

**Comment by apap04** [comment]
pls merge

**Comment by apap04** [comment]
aaaaaaaaaaaaaaaaaaaaaa

**Comment by Shibe43** [comment]
STOP CHATTING U NIGGER

**Comment by apap04** [comment]
make me

**Comment by oktres** [comment]
hi.

**Comment by oktres** [comment]
hi
its me tres
tres#6555
hi
hi
hi

**Comment by apap04** [comment]
hi

**Pull request merged**
